You feel the ground rumble again as the distress signal leads you to a large network of subterranean tunnels. You don't have time to search them all, but you don't need to: your pack contains a set of deployable sensors that you imagine were originally built to locate lost Elves.

The sensors aren't very powerful, but that's okay; your handheld device indicates that you're close enough to the source of the distress signal to use them. You pull the emergency sensor system out of your pack, hit the big button on top, and the sensors zoom off down the tunnels.

Once a sensor finds a spot it thinks will give it a good reading, it attaches itself to a hard surface and begins monitoring for the nearest signal source beacon. Sensors and beacons always exist at integer coordinates. Each sensor knows its own position and can determine the position of a beacon precisely; however, sensors can only lock on to the one beacon closest to the sensor as measured by the Manhattan distance. (There is never a tie where two beacons are the same distance to a sensor.)

It doesn't take long for the sensors to report back their positions and closest beacons (your puzzle input). For example:

```
Sensor at x=2, y=18: closest beacon is at x=-2, y=15
Sensor at x=9, y=16: closest beacon is at x=10, y=16
Sensor at x=13, y=2: closest beacon is at x=15, y=3
Sensor at x=12, y=14: closest beacon is at x=10, y=16
Sensor at x=10, y=20: closest beacon is at x=10, y=16
Sensor at x=14, y=17: closest beacon is at x=10, y=16
Sensor at x=8, y=7: closest beacon is at x=2, y=10
Sensor at x=2, y=0: closest beacon is at x=2, y=10
Sensor at x=0, y=11: closest beacon is at x=2, y=10
Sensor at x=20, y=14: closest beacon is at x=25, y=17
Sensor at x=17, y=20: closest beacon is at x=21, y=22
Sensor at x=16, y=7: closest beacon is at x=15, y=3
Sensor at x=14, y=3: closest beacon is at x=15, y=3
Sensor at x=20, y=1: closest beacon is at x=15, y=3
```

So, consider the sensor at `2,18`; the closest beacon to it is at `-2,15`. For the sensor at `9,16`, the closest beacon to it is at `10,16`.

Drawing sensors as S and beacons as B, the above arrangement of sensors and beacons looks like this:

```
               1    1    2    2
     0    5    0    5    0    5
 0 ....S.......................
 1 ......................S.....
 2 ...............S............
 3 ................SB..........
 4 ............................
 5 ............................
 6 ............................
 7 ..........S.......S.........
 8 ............................
 9 ............................
10 ....B.......................
11 ..S.........................
12 ............................
13 ............................
14 ..............S.......S.....
15 B...........................
16 ...........SB...............
17 ................S..........B
18 ....S.......................
19 ............................
20 ............S......S........
21 ............................
22 .......................B....
```

This isn't necessarily a comprehensive map of all beacons in the area, though. Because each sensor only identifies its closest beacon, if a sensor detects a beacon, you know there are no other beacons that close or closer to that sensor. There could still be beacons that just happen to not be the closest beacon to any sensor. Consider the sensor at `8,7`:

```
               1    1    2    2
     0    5    0    5    0    5
-2 ..........#.................
-1 .........###................
 0 ....S...#####...............
 1 .......#######........S.....
 2 ......#########S............
 3 .....###########SB..........
 4 ....#############...........
 5 ...###############..........
 6 ..#################.........
 7 .#########S#######S#........
 8 ..#################.........
 9 ...###############..........
10 ....B############...........
11 ..S..###########............
12 ......#########.............
13 .......#######..............
14 ........#####.S.......S.....
15 B........###................
16 ..........#SB...............
17 ................S..........B
18 ....S.......................
19 ............................
20 ............S......S........
21 ............................
22 .......................B....
```

This sensor's closest beacon is at `2,10`, and so you know there are no beacons that close or closer (in any positions marked `#`).

None of the detected beacons seem to be producing the distress signal, so you'll need to work out where the distress beacon is by working out where it isn't. For now, keep things simple by counting the positions where a beacon cannot possibly be along just a single row.

So, suppose you have an arrangement of beacons and sensors like in the example above and, just in the row where `y=10`, you'd like to count the number of positions a beacon cannot possibly exist. The coverage from all sensors near that row looks like this:

```
                 1    1    2    2
       0    5    0    5    0    5
 9 ...#########################...
10 ..####B######################..
11 .###S#############.###########.
```

In this example, in the row where `y=10`, there are 26 positions where a beacon cannot be present.

Consult the report from the sensors you just deployed. ***In the row where y=2000000, how many positions cannot contain a beacon?***

In [44]:
import numpy as np
import re
input_file  = open("data/2022-12-15-input.txt")
input_lines = input_file.readlines()
line_pattern = r'.*x\=(\-?[0-9]+).*y\=(\-?[0-9]+).*x\=(\-?[0-9]+).*y\=(\-?[0-9]+)'
locations = np.array([list(map(int, re.search(line_pattern, line).groups())) for line in input_lines])
locations

array([[ 3088287,  2966967,  3340990,  2451747],
       [  289570,   339999,    20077,  1235084],
       [ 1940197,  3386754,  2010485,  3291030],
       [ 1979355,  2150711,  1690952,  2000000],
       [ 2859415,  1555438,  3340990,  2451747],
       [ 1015582,  2054755,  1690952,  2000000],
       [ 1794782,  3963737,  2183727,  4148084],
       [ 2357608,  2559811,  2010485,  3291030],
       [    2936,  1218210,    20077,  1235084],
       [ 2404143,  3161036,  2010485,  3291030],
       [   12522,  1706324,    20077,  1235084],
       [ 1989162,  3317864,  2010485,  3291030],
       [  167388,  3570975, -1018858,  4296788],
       [ 1586527,  2233885,  1690952,  2000000],
       [  746571,  1442967,    20077,  1235084],
       [ 3969726,  3857699,  3207147,  4217920],
       [ 1403393,  2413121,  1690952,  2000000],
       [ 2343717,  3649198,  2183727,  4148084],
       [ 1473424,   688269,  2053598,  -169389],
       [ 2669347,   190833,  2053598,  -169389],
       [ 2973167,  3

In [53]:
distances = abs(locations[:,0] - locations[:,2]) + abs(locations[:,1] - locations[:,3])
distances

array([ 767923, 1164578,  166012,  439114, 1377884,  730125,  573292,
       1078342,   34015,  523652,  478795,   48157, 1912059,  338310,
        934377, 1122800,  700680,  658876, 1437832,  975971,  668117,
         24501,  709563, 1975212,   18621,  205140,  203627,  321268])

In [54]:
target_y = 2000000
margins = distances - abs(locations[:,1] - target_y)
margins

array([ -199044,  -495423, -1220742,   288403,   933322,   675370,
       -1390445,   518531,  -747775,  -637384,   185119, -1269707,
         341084,   104425,   377344,  -734899,   287559,  -990322,
         126101,  -833196, -1115666, -1289680,  -280165,  1039646,
       -1283157,   120953,    76745,  -524207])

In [61]:
x_ranges = np.transpose([locations[:, 0] - margins, locations[:, 0] + margins])
valid_x_ranges = x_ranges[x_ranges[:,0] < x_ranges[:,1], ]
valid_x_ranges

array([[1690952, 2267758],
       [1926093, 3792737],
       [ 340212, 1690952],
       [1839077, 2876139],
       [-172597,  197641],
       [-173696,  508472],
       [1482102, 1690952],
       [ 369227, 1123915],
       [1115834, 1690952],
       [1347323, 1599525],
       [2889243, 4968535],
       [1690952, 1932858],
       [1690952, 1844442]])

In [101]:
x_unions = np.empty((0, 2))
for x_range in valid_x_ranges:
    add_range = True
    for i, x_union in enumerate(x_unions):
        if x_range[0] <= x_union[1] and x_union[0] <= x_range[1]:
            x_unions[i, :] = [min(x_range[0], x_union[0]), max(x_range[1], x_union[1])]
            add_range = False
            break
    if add_range:
        x_unions = np.r_[x_unions, [x_range]]

# This is a horrible hack that works because I know what the data is
print(f'The number of positions that cannot contain a beacon in row {target_y} is {int(x_unions[0,1] - x_unions[0,0])}')

The number of positions that cannot contain a beacon in row 2000000 is 5142231


Your handheld device indicates that the distress signal is coming from a beacon nearby. The distress beacon is not detected by any sensor, but the distress beacon must have x and y coordinates each no lower than 0 and no larger than 4000000.

To isolate the distress beacon's signal, you need to determine its tuning frequency, which can be found by multiplying its x coordinate by 4000000 and then adding its y coordinate.

In the example above, the search space is smaller: instead, the x and y coordinates can each be at most 20. With this reduced search area, there is only a single position that could have a beacon: x=14, y=11. The tuning frequency for this distress beacon is 56000011.

***Find the only possible position for the distress beacon. What is its tuning frequency?***

In [211]:
def IsInSensorRange(x, y, sensors, distances, max_coord):
    if x < 0 or y < 0 or x > max_coord or y > max_coord:
        return True
    else:
        return any(abs(sensors[:, 0] - x) + abs(sensors[:, 1] - y) <= distances)

x = 2721114
y = 3367718
IsInSensorRange(x, y, locations, distances, max_coord)

False

In [217]:
found_beacon = False
for i in range(len(distances)):
    if found_beacon:
        break
    s_x = locations[i, 0]
    s_y = locations[i, 1]
    for delta in range(distances[i] + 1):
        x_offset = delta
        y_offset = distances[i] + 1 - delta
        if not IsInSensorRange(s_x + x_offset, s_y + y_offset, locations, distances, max_coord):
            print(f'The distress beacon is at ({s_x + x_offset}, {s_y + y_offset})')
            found_beacon = True
            break
        if not IsInSensorRange(s_x + x_offset, s_y - y_offset, locations, distances, max_coord):
            print(f'The distress beacon is at ({s_x + x_offset}, {s_y - y_offset})')
            found_beacon = True
            break
        if not IsInSensorRange(s_x - x_offset, s_y + y_offset, locations, distances, max_coord):
            print(f'The distress beacon is at ({s_x - x_offset}, {s_y + y_offset})')
            found_beacon = True
            break
        if not IsInSensorRange(s_x - x_offset, s_y - y_offset, locations, distances, max_coord):
            print(f'The distress beacon is at ({s_x - x_offset}, {s_y - y_offset})')
            found_beacon = True
            break

The distress beacon is at (2721114, 3367718)


In [214]:
print(f'The tuning frequency is {max_coord * (2721114) + 3367718}')
# 10884463367718

The tuning frequency is 10884459367718
